config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :categories, only: [:index, :create, :new] do
    resources :records, only: [:index, :create, :new]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_transactions, dependent: :destroy
  has_many :records, through: :category_transactions

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :record
  belongs_to :category
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :category_transactions, dependent: :destroy
  has_many :categories, through: :category_transactions

  validates :name, presence: true
  validates :amount, numericality: { only_integer: false, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.includes(:categories).find(current_user.id)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to categories_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  def index
    category = Category.includes(:records).find(params[:category_id])
    @records = category.records.order(created_at: :desc)
  end

  def new
    @record = Record.new
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
  end

  def create
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
    params = records_params
    @record = Record.new(name: params[:name], amount: params[:amount])
    @record.user = current_user
    @categories_ids = params[:category_ids]
    @categories_ids.each do |id|
      category = Category.find(id) unless id == ''
      @record.categories << category unless category.nil?
    end
    if @record.save
      redirect_to category_records_path(@record.categories.first.id)
    else
      render 'new'
    end
  end

  private

  def records_params
    params.require(:record).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
 <div class='errors'>
    <h2>The following errors must be resolved</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div> 
<% end %>
<%= form_with model: @category, url: categories_path, data: { turbo: false }, method: :post do |f| %>

<div class='input_contain'>
  <div class='input_label'> 
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>

  <div class='input_label'>
    <%= f.url_field :icon, placeholder: 'Icon link' %>
  </div>
    
  <%= f.submit('Save', class: "add_btn") %> 
</div>

<% end %>

app/views/categories/index.html.erb
<div class='categories_container'>
  <% if @user.categories.empty? %>
    <h2 class='empty'> No Categories for this user.</h2>
  <% else %>
      <ul class='category_list'> 
        <% @user.categories.each do |category| %>
           <li>
            <a href="<%=category_records_path(category.id)%>">
              <div class='image'>
                <img src='<%= category.icon %>' alt='<%= category.name %>'/>
              </div>  
              <div class='info'>
               <div>
                <p class='category_name'><%= category.name %></p>
                <% if category.records.empty? %>
                <p class='total_amounts'>$0</p>
                <% else %>
                <p class='total_amounts'>$<%= category.records.inject(0) {|sum,x| sum + x.amount } %></p>
                <% end %>
               </div> 
               <p><%= category.created_at.strftime("%d %b %Y") %></p>
              </div>
            </a>
           </li>
        <% end %>
      </ul> 
  <% end %>
  <div class='add_category_cover'>
   <%= link_to 'Add a new category', new_category_path, class: 'add_category' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class='add_container'>
    <%= link_to '< back', categories_path, class: 'back' %>

    <%= render 'form' %>
</div>

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/home/index.html.erb
<div class='home_container'>
    <h1>Budgetty</h1>
    <div>
    <%= link_to 'LOG IN',  new_user_session_path , class: 'sign_in' %>
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'sign_up' %>
    </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/records/_form.html.erb
<% if @record.errors.any? %>
 <div class='errors'>
    <h2>The following errors must be resolved</h2>
    <ul>
    <% @record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div> 
<% end %>
<%= form_with model: @record, url: category_records_path(@category.id), data: { turbo: false }, method: :post do |f| %>

  <div class='input_contain'>
    <div class='input_label'>
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>

    <div class='input_label'>
      <%= f.text_field :amount, placeholder: 'Amount' %>
    </div>

    <div class='select_label'>
      <%= f.label :categories, 'Please select at least one(use `shift` or `ctrl` key for multiple)' %>
      <%= f.collection_select(:category_ids, @categories, :id, :name, {}, :multiple => true, :required => true, size: @categories.length) %>
    </div>
    <%= f.submit('Save', class: "add_btn") %> 
  </div>

<% end %>

app/views/records/index.html.erb
<div class='categories_container'>
  <div class='back_total'>
    <%= link_to '< back', categories_path, class: 'back2' %>
    <h3>$<%= @records.inject(0) {|sum,x| sum + x.amount } || 0 %></h3>
  </div>
  <% if @records.empty? %>
    <h2 class='empty'> No transactions for this category.</h2>
  <% else %>
      <ul class='record_list'> 
        <% @records.each do |record| %>
           <li>
            <p class='category_name'><%= record.name %></p>
            <p>$<%= record.amount %></p>
           </li>
        <% end %>
      </ul>  
    </table>
      
  <% end %>
  <div class='add_category_cover'>
    <%= link_to 'Add new transaction', new_category_record_path, class: 'add_category' %>
  </div>
</div>

app/views/records/new.html.erb
<div class='add_container'>
    <%= link_to '< back', category_records_path(@category.id),class: 'back' %>

    <%= render 'form' %>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class= 'nav_bar'>
   <h2>Budgetty</h2>
   <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
  </nav>
<% end %>